name: Mobile/Traffic Director

permissions:
  contents: read

on:
  schedule:
  # Once a day at midnight.
  - cron: '0 0 * * *'
  # Allows manual triggering in the UI. Makes it easier to test.
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-github.workflow
  cancel-in-progress: true

jobs:
  cc-tests:
    if: ${{ fromJSON(needs.load.outputs.request).run.mobile-traffic-director }}
    name: cc-tests
    uses: ./.github/workflows/_mobile_container_ci.yml
    secrets:
      gcp-traffic-key: ${{ secrets.GCP_TEST_PROJECT_API_KEY }}
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
    with:
      args: >-
        run
        --config=mobile-remote-ci
        --config=ci
        --test_env=ENVOY_IP_TEST_VERSIONS=v4only
        //test/non_hermetic:gcp_traffic_director_integration_test
      request: ${{ needs.load.outputs.request }}
      target: cc-tests
      timeout-minutes: 90
