name: Mobile/Traffic Director

permissions:
  contents: read

on:
  schedule:
  # Once a day at midnight.
  - cron: '0 0 * * *'
  # Allows manual triggering in the UI. Makes it easier to test.
  workflow_dispatch:

jobs:
  cc-tests:
    permissions:
      contents: read
      statuses: read
    name: Traffic Director
    runs-on: ubuntu-22.04
    if: >-
      ${{
          github.repository == 'envoyproxy/envoy'
          && (github.event.schedule
              || !contains(github.actor, '[bot]'))
      }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Traffic Director integration test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GCP_TEST_PROJECT_PROD_API_KEY: ${{ secrets.GCP_TEST_PROJECT_PROD_API_KEY }}
        ENVOY_IP_TEST_VERSIONS: v4only
      run: |
        cd mobile
        ./bazelw run \
            --config=mobile-remote-ci \
            --config=ci \
            //test/non_hermetic:gcp_traffic_director_integration_test
    # with:
    #   args: >-
    #     run
    #     --config=mobile-remote-ci
    #     --config=ci
    #     --test_env=ENVOY_IP_TEST_VERSIONS=v4only
    #     //test/non_hermetic:gcp_traffic_director_integration_test
    #   request: ${{ needs.load.outputs.request }}
    #   target: cc-tests
    #   timeout-minutes: 90
