name: Mobile/Traffic Director

permissions:
  contents: read

on:
  schedule:
  # Once a day at midnight.
  - cron: '0 0 * * *'
  # Allows manual triggering in the UI. Makes it easier to test.
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-github.workflow
  cancel-in-progress: true

jobs:
  load:
    secrets:
      app-key: ${{ secrets.ENVOY_CI_APP_KEY }}
      app-id: ${{ secrets.ENVOY_CI_APP_ID }}
      lock-app-key: ${{ secrets.ENVOY_CI_MUTEX_APP_KEY }}
      lock-app-id: ${{ secrets.ENVOY_CI_MUTEX_APP_ID }}
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_load.yml
    with:
      check-name: mobile-traffic-director

  cc_test:
    if: ${{ fromJSON(needs.load.outputs.request).run.mobile-traffic-director }}
    needs: load
    name: cc-tests
    uses: ./.github/workflows/_mobile_container_ci.yml
    secrets:
      GCP_TEST_PROJECT_API_KEY: ${{ fromJSON(needs.load.outputs.trusted) && secrets.GCP_TEST_PROJECT_API_KEY || '' }}
    with:
      args: >-
        run
        --config=mobile-remote-ci
        --config=ci
        //test/non_hermetic:gcp_traffic_director_integration_test
      request: ${{ needs.load.outputs.request }}
      target: cc-tests
      timeout-minutes: 90

  request:
    secrets:
      app-id: ${{ secrets.ENVOY_CI_APP_ID }}
      app-key: ${{ secrets.ENVOY_CI_APP_KEY }}
    permissions:
      actions: read
      contents: read
    if: >-
      ${{ always()
          && github.event.workflow_run.conclusion == 'success'
          && fromJSON(needs.load.outputs.request).run.mobile-traffic-director }}
    needs:
    - load
    - cc-tests
    uses: ./.github/workflows/_finish.yml
    with:
      needs: ${{ toJSON(needs) }}
